# This docker-compose file provides quick setups for testing different storage backend options.
version: "3.8"

services:
    mysql:
        # For using percona-xtradb you need to make strict mode permissive with:
        # docker-compose exec mysql mysql -uroot -proot -e "SET GLOBAL pxc_strict_mode=PERMISSIVE;"
        # See: https://www.percona.com/doc/percona-xtradb-cluster/5.7/features/pxc-strict-mode.html
        # image: percona/percona-xtradb-cluster:5.7
        # image: mariadb:10.5
        # image: mysql:5.6
        # image: mysql:8.0
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: dex
            MYSQL_USER: mysql
            MYSQL_PASSWORD: mysql
            MYSQL_ROOT_PASSWORD: root

    postgres:
        image: postgres:10.15
        environment:
            POSTGRES_DB: dex
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres

    etcd:
        image: gcr.io/etcd-development/etcd:v3.5.0
        environment:
            ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
            ETCD_ADVERTISE_CLIENT_URLS: http://0.0.0.0:2379

    # For testing the Kubernetes storage backend we suggest https://kind.sigs.k8s.io/:
    # kind create cluster

    ldap:
        image: osixia/openldap:1.4.0
        # Copying is required because the entrypoint modifies the *.ldif files.
        # For verbose output, use:  command: ["--copy-service", "--loglevel", "debug"]
        command: ["--copy-service"]
        environment:
            LDAP_BASE_DN: "dc=example,dc=org"
            LDAP_TLS: "true"
            LDAP_TLS_VERIFY_CLIENT: try
        volumes:
            - ./connector/ldap/testdata/certs:/container/service/slapd/assets/certs
            - ./connector/ldap/testdata/schema.ldif:/container/service/slapd/assets/config/bootstrap/ldif/99-schema.ldif

    vault:
        image: hashicorp/vault:1.21
        environment:
            VAULT_DEV_ROOT_TOKEN_ID: root-token
            VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
        cap_add:
            - IPC_LOCK
        ports:
            - 8200:8200

    openbao:
        image: quay.io/openbao/openbao:2.5
        environment:
            BAO_DEV_ROOT_TOKEN_ID: root-token
            BAO_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
        cap_add:
            - IPC_LOCK
        ports:
            - 8210:8200
