kind: OAuth2Client
apiVersion: oauth2clients.oidc.coreos.com/v1
metadata:
  name: example-app
  namespace: default

secret: ZXhhbXBsZS1hcHAtc2VjcmV0
redirectURIs:
- http://127.0.0.1:5555/callback
name: Example App
