blank_issues_enabled: false
contact_links:
  - name: ğŸ“– Documentation enhancement
    url: https://github.com/dexidp/website/issues
    about: Suggest an improvement to the documentation

  - name: â“ Ask a question
    url: https://github.com/dexidp/dex/discussions/new?category=q-a
    about: Ask and discuss questions with other Dex community members

  - name: ğŸ“š Documentation
    url: https://dexidp.io/docs/
    about: Check the documentation for help

  - name: ğŸ’¬ Slack channel
    url: https://cloud-native.slack.com/messages/dexidp
    about: Please ask and answer questions here

  - name: ğŸ’¡ Dex Enhancement Proposal
    url: https://github.com/dexidp/dex/tree/master/docs/enhancements/README.md
    about: Open a proposal for significant architectural change
