apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: connectors.dex.coreos.com
spec:
  group: dex.coreos.com
  names:
    kind: Connector
    listKind: ConnectorList
    plural: connectors
    singular: connector
  version: v1
