apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: devicetokens.dex.coreos.com
spec:
  group: dex.coreos.com
  names:
    kind: DeviceToken
    listKind: DeviceTokenList
    plural: devicetokens
    singular: devicetoken
  version: v1
