apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: offlinesessionses.dex.coreos.com
spec:
  group: dex.coreos.com
  names:
    kind: OfflineSessions
    listKind: OfflineSessionsList
    plural: offlinesessionses
    singular: offlinesessions
  version: v1
