apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: passwords.dex.coreos.com
spec:
  group: dex.coreos.com
  names:
    kind: Password
    listKind: PasswordList
    plural: passwords
    singular: password
  version: v1
