apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: signingkeies.dex.coreos.com
spec:
  group: dex.coreos.com
  names:
    kind: SigningKey
    listKind: SigningKeyList
    plural: signingkeies
    singular: signingkey
  version: v1
